resource "aws_bedrock_guardrail" "guardrail" {
  provider                  = aws.west2
  name                      = "${var.bot_name}Guardrail"
  blocked_input_messaging   = "Your input has been blocked by our content filter. Please try again. If this is an error, discuss with the DevOps team."
  blocked_outputs_messaging = "The output generated by our system has been blocked by our content filter. Please try again. If this is an error, discuss with the DevOps team."
  description               = "${var.bot_name} Guardrail"

  content_policy_config {
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "INSULTS"
    }
    filters_config {
      input_strength  = "LOW"
      output_strength = "MEDIUM"
      type            = "MISCONDUCT"
    }
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "SEXUAL"
    }
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "VIOLENCE"
    }
    filters_config {
      input_strength  = "NONE"
      output_strength = "NONE"
      type            = "PROMPT_ATTACK"
    }
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "HATE"
    }
  }

  sensitive_information_policy_config {
    pii_entities_config {
      action = "ANONYMIZE"
      type   = "US_SOCIAL_SECURITY_NUMBER"
    }
  }

  # topic_policy_config {
  #   topics_config {
  #     name       = "investment_topic"
  #     examples   = ["Where should I invest my money ?"]
  #     type       = "DENY"
  #     definition = "Investment advice refers to inquiries, guidance, or recommendations regarding the management or allocation of funds or assets with the goal of generating returns."
  #   }
  # }

  # word_policy_config {
  #   managed_word_lists_config {
  #     type = "PROFANITY"
  #   }
  # }
}